# Generated by Django 4.1.3 on 2022-11-19 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'country',
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_code', models.CharField(max_length=50)),
                ('pathogen', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=140)),
            ],
            options={
                'verbose_name_plural': 'disease',
                'db_table': 'disease',
            },
        ),
        migrations.CreateModel(
            name='DiseaseType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=140, null=True)),
            ],
            options={
                'verbose_name_plural': 'Disease Type',
                'db_table': 'disease_type',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='PublicServant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'public_servant',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=40)),
                ('salary', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=20)),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.country')),
            ],
            options={
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Specialize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.diseasetype')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.doctor')),
            ],
            options={
                'db_table': 'specialize',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_deaths', models.IntegerField()),
                ('total_patients', models.IntegerField()),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.country')),
                ('disease_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.disease')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.publicservant')),
            ],
            options={
                'db_table': 'record',
            },
        ),
        migrations.AddField(
            model_name='publicservant',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.users'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.users'),
        ),
        migrations.AddField(
            model_name='disease',
            name='disease_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.diseasetype'),
        ),
        migrations.CreateModel(
            name='Discover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_enc', models.DateField()),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.country')),
                ('disease_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.disease')),
            ],
            options={
                'db_table': 'discover',
            },
        ),
    ]
